### ISSUE TITLE
User table not created correctly

### ISSUE THREAD

**Issue by jl-678** [pashcovich/openvpn-user#4]
I was setting up ovpn-admin along with ovpn-user and ran into issues and a bug related to ovpn-user.  Specifically, the issue is that it is not clearly documented that you first need to run:

openvpn-user --db.path="<path to db>" db-init

Once I ran the above command to create the database, I encountered a bug.  Specifically, the resulting DB was missing the columns "secret" and "app_configured".  These columns are required and caused ovpn-admin to refuse to add new users. The problem is in [this file](https://github.com/pashcovich/openvpn-user/blob/master/src/commands.go), and you can see that those two columns are not included when the DB is created. (You will note that the next function creating users includes those missing fields in the INSERT statement which causes the error.)

The good news is that I am reasonably handy with sqlite and so added those columns manually.  Once I did that, everything worked as expected.

**Comment by xmanag3r** [comment]
Can you please let me know how did you fix @jl-678 ?

**Comment by jl-678** [comment]
The database used is sqlite and you can easily get a client from your repo of choice. Open up the db, and add "secret" and "app_configured" to the "users" table.

This is the path to the DB on my instance: /etc/openvpn/ovpn-admin/ and the database is called openvpn-user.db.
I suggest that you make sure that you backup the file before making changes.

**Comment by pashcovich** [comment]
https://github.com/pashcovich/openvpn-user/pull/3#issuecomment-1361390193
